Created a buildController for PR purposes.
cppwfs/toupperish pull request #1
Opened 2024-12-04 22:21 UTC by cppwfs

It is called buildController-for-review.sh.

Once it meets Review standards we will delte the original buildController script and rename this one

2024-12-04 22:29 UTC, onobc commented on scripts/buildController-for-review.sh
> +# Set variables for repositories and workflows
We will want to move these to inputs w/ validation and usage. I am sure you already know this, just doing my due diligence...

2024-12-04 22:30 UTC, onobc commented on scripts/buildController-for-review.sh
> +    echo "WF_ID=$WF_ID"
Add validation that the WF_ID is not null

2024-12-04 22:31 UTC, onobc commented on scripts/buildController-for-review.sh
> +    while [ "$RUN_ID" = "" ]; do
We don't want to spin forever as the RUN_ID will be available pretty quickly. Maybe 20s max??

2024-12-04 22:32 UTC, onobc commented on scripts/buildController-for-review.sh
> +      echo "RUN_ID=$RUN_ID"
If `RUN_ID` is `""` probably don't want to echo it

2024-12-04 22:33 UTC, onobc commented on scripts/buildController-for-review.sh
> +    gh run --repo "$WF_REPO" watch $RUN_ID -i 10
Does `watch` have a max wait time? I can see this taking a decent amount of time but we should constrain it somehow.

2024-12-04 22:33 UTC, onobc commented on scripts/buildController-for-review.sh
> +    gh run --repo "$WF_REPO" view $RUN_ID --log --exit-status
I think we can delete this line as its done in next line

2024-12-04 22:34 UTC, onobc commented on scripts/buildController-for-review.sh
> +echo "Launching workflow in $REPO_A..."
I would include `$WF_PATH_A $BRANCH_A`

2024-12-04 22:35 UTC, onobc requested changes
Looking good @cppwfs . Some comments around  max wait times and improved logging.. Other than that LGTM

2024-12-05 22:58 UTC, cppwfs commented on scripts/buildController-for-review.sh
> +    gh run --repo "$WF_REPO" watch $RUN_ID -i 10
Unfortunately no 😞

2024-12-06 15:30 UTC, onobc commented
> It is called buildController-for-review.sh.
> 
> Once it meets Review standards we will delte the original buildController script and rename this one

FWIW I like `run-workflow.sh`

2024-12-06 16:08 UTC, onobc commented on scripts/buildController-for-review.sh
> +  echo "This Script will execute the specified group of workflows passed in via command line args"
`s/This Script will execute/Executes`

2024-12-06 16:11 UTC, onobc commented on scripts/buildController-for-review.sh
> +    process_comma_delimited_list "$element"
Nit but I think if a function name like `process_workflow_input _tuple` may be a bit more readable

2024-12-06 16:12 UTC, onobc commented on scripts/buildController-for-review.sh
> +    arraySize=${#workflow[@]}
All below here needs left indent

2024-12-06 16:13 UTC, onobc commented on scripts/buildController-for-review.sh
> +    arraySize=${#workflow[@]}
I thought this needed to be indented but now I am confused as to what is happennig

2024-12-06 16:15 UTC, onobc commented on scripts/run-workflow.sh
> +process_comma_delimited_list() {
I would move this down closer to where its used

2024-12-06 16:15 UTC, onobc commented on scripts/run-workflow.sh
> +workflow=()
Maybe naming this `workflowInputTuple` would make it easier to follow?

2024-12-06 16:16 UTC, cppwfs commented on scripts/buildController-for-review.sh
> +    arraySize=${#workflow[@]}
It shouldn't be indented.
Lines 83-96 will be shifted to the left one tab.

2024-12-06 16:16 UTC, onobc commented on scripts/run-workflow.sh
> +# Function to extract each item from comma delimited list
Function to extract a workflow input tuple into 3 elements in the output variable `workflowInputTuple`

2024-12-06 16:17 UTC, onobc commented on scripts/run-workflow.sh
> +  done
Is this `done` supposed to be here?

2024-12-06 16:18 UTC, onobc commented on scripts/run-workflow.sh
> +    arraySize=${#workflow[@]}
I think moving this validation into the `process_workflow_input_tuple` method would simplify things

2024-12-06 16:18 UTC, cppwfs commented on scripts/buildController-for-review.sh
> +    arraySize=${#workflow[@]}
The main is a loop that goes through each of the workflow groups.
For each workflow group it extracts the repo,branch,workflow.yml file for the workflow group.   Then runs the workflow based on this information.

I can add a comment.

2024-12-06 16:21 UTC, onobc commented on scripts/buildController-for-review.sh
> +    arraySize=${#workflow[@]}
Bash sucks! I get it now. I made some comment on method and var renames that will make it a bit easier to follow.

2024-12-06 16:27 UTC, onobc commented on scripts/run-workflow.sh
> +  echo "A workflow is specified in a comma delimited format as follows: REPOSITORY,BRANCH,NAME_OF_THE_WORKFLOW_YAML_FILE"
I would replace this with a "usage()" function that was a little more robotic and less personal. Something like:

```
Executes one or workflows in serial fail-fast fashion.

usage: ./run-workflow.sh [workflow-tuple]*
    where [workflow-tuple] is a csv string of workflow coordinates in the form
         "repo,branch,workflow" (e.g. "my-repo,main,my-pr.yml")

```
Wdyt?

2024-12-06 16:30 UTC, cppwfs commented on scripts/run-workflow.sh
> +  done
Yes.  This where we extract the repo, branch, workflow.yml file data from each element.
For example `cppwfs/toupperish,main,foo.yml spring-cloud/spring-cloud-dataflow,main,bar.yml`
Will produce 2 elements.  Each element will have the repo, branch,and workflowyaml.

2024-12-06 16:37 UTC, onobc commented on scripts/run-workflow.sh
> +  done
Oh this is that terrible IFS csv that bash uses.... I get it now. Maybe rename `elements` and `element` as that is a very generic name. 

What I would do is abstract everything from 76-87 in a function called `parse_input_tuple_into_workflow_coordinates`. really we are looping through N tuple-csv-strings and for each one we want 3 fields (thought is "don't care what nasty things you have to do to get it just give me the output" :)

2024-12-06 19:51 UTC, onobc commented on scripts/run-workflow.sh
> +  echo '    "repo,branch,workflow" (e.g. "my-repo,main,my-pr.yml")'
Only in bash do you have one string line starting w/ `"` and the next starting w/ `'` (and I know exactly why you had to do it).

2024-12-06 19:54 UTC, onobc commented on scripts/run-workflow.sh
> +    if [ -z "${WF_ID}" ]; then
The missing piece always w/ these bash script (for me anyways) is how to test them. Yeh, the answer is manually. That being said, the 1000 different ways to check if an arg is empty or null or ... I would definitely manually test this by setting WF_ID ="" and WF_ID= and making sure it does what you think. I think it does but I never trust these operators unless I see it.

2024-12-06 19:58 UTC, onobc commented on scripts/run-workflow.sh
> +    IFS=',' read -ra elements <<< "$arg"
Ahh yes, the magic of "what in the hell is 'arg' and where did it come from? AHh yes, bash I hate you.

I prefer to pass the arg in such as this:
```
process_workflow_input_tuple() {
    inputTuple = $1
   ...
}
```
and to call it....
```
process_workflow_input_tuple arg
```

Wdyt?

2024-12-06 19:59 UTC, onobc commented on scripts/run-workflow.sh
> +    IFS=',' read -ra elements <<< "$arg"
Moving this to the function definitely cleans up the main method.

2024-12-06 20:00 UTC, onobc commented on scripts/run-workflow.sh
> +  repository=${workflowInputTuple[0]}
**[TinyNit]** indentation off below

2024-12-06 20:03 UTC, onobc commented on scripts/run-workflow.sh
> +  workflowInputTuple=()
Oh my bash!!!  hehe

I think we can move this to line 65. I know it has to be defined outside of the function at least once (which it is on 62). That way it keeps that to an internal concern.

2024-12-06 20:06 UTC, cppwfs commented on scripts/run-workflow.sh
> +  echo '    "repo,branch,workflow" (e.g. "my-repo,main,my-pr.yml")'
Don't tell my mom :-)

2024-12-06 21:18 UTC, cppwfs commented on scripts/run-workflow.sh
> +    if [ -z "${WF_ID}" ]; then
Kicked the tires and It checks for null and empty successfully.

2024-12-06 21:22 UTC, merged